services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\PrismicApi\:
        resource: ../src/*
        exclude: ../src/{Data,Exception,PrismicApiBundle.php}

    Torr\PrismicApi\Api\PrismicApi:
        $repository: '%env(PRISMIC_REPOSITORY)%'
        $contentToken: '%env(PRISMIC_CONTENT_API_TOKEN)%'
        $typesToken: '%env(PRISMIC_TYPES_API_TOKEN)%'

    Torr\PrismicApi\CustomType\CustomTypesMigrator:
        $typeDefinitions: !tagged_iterator 'prismic.type-definition'

    Torr\PrismicApi\RichText\LinkGenerator:
        $handlers: !tagged_iterator 'prismic.link_generator'
