services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\PrismicApi\:
        resource: ../src/*
        exclude:
            - '../src/Data'
            - '../src/Definition'
            - '../src/Document/Data'
            - '../src/Editor'
            - '../src/Exception'
            - '../src/PrismicApiBundle.php'
            - '../src/Structure'

    Torr\PrismicApi\Api\PrismicApi:
        $repository: '%env(PRISMIC_REPOSITORY)%'
        $contentToken: '%env(PRISMIC_CONTENT_API_TOKEN)%'
        $typesToken: '%env(PRISMIC_TYPES_API_TOKEN)%'

    Torr\PrismicApi\Migration\TypesMigrator:
        $documentDefinitions: !tagged_iterator 'prismic.document.definition'

    Torr\PrismicApi\Factory\DocumentFactory:
        $documentDefinitions: !tagged_iterator 'prismic.document.definition'

    Torr\PrismicApi\RichText\LinkGenerator:
        $handlers: !tagged_iterator 'prismic.link_generator'

    Torr\PrismicApi\Api\PrismicIntegrationFieldApi:
        $repository: '%env(PRISMIC_REPOSITORY)%'
        $tokens: '%env(json:PRISMIC_INTEGRATION_TOKENS)%'

    Torr\PrismicApi\Transform\DataTransformer:
        $sliceExtraDataGenerators: !tagged_iterator 'prismic.slice.extra-data-generator'

    Torr\PrismicApi\Url\PrismicBackendUrlGenerator:
        $repository: '%env(PRISMIC_REPOSITORY)%'
