services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\PrismicApi\:
        resource: ../src/*
        exclude:
            - '../src/Data'
            - '../src/DependencyInjection'
            - '../src/Document/Data'
            - '../src/CustomType/Data'
            - '../src/Exception'
            - '../src/PrismicApiBundle.php'
            - '../src/Validation'

    Torr\PrismicApi\Api\PrismicApi:
        $repository: '%env(PRISMIC_REPOSITORY)%'
        $contentToken: '%env(PRISMIC_CONTENT_API_TOKEN)%'
        $typesToken: '%env(PRISMIC_TYPES_API_TOKEN)%'

    Torr\PrismicApi\CustomType\CustomTypesMigrator:
        $documentDefinitions: !tagged_iterator 'prismic.document.definition'

    Torr\PrismicApi\Factory\DocumentFactory:
        $documentTypes: !tagged_iterator 'prismic.document.definition'

    Torr\PrismicApi\RichText\LinkGenerator:
        $handlers: !tagged_iterator 'prismic.link_generator'
